### ISSUE TITLE
楼主你这里用的cudnn_rnn.CudnnGRU函数默认的activation函数是什么啊，或者如果不在外面加个层的化怎么设置activation

### ISSUE THREAD

**Issue by fudanchenjiahao** [shiningliang/MRC2018#3]

**Comment by shiningliang** [comment]
我之前一路追踪源码但是并没有看到，因为TF用的cudnn_RNN很原生态。。。有人向keras官方提问过[类似的问题](https://github.com/keras-team/keras/issues/8510)，看起来是遵从原始实现，内部sigmoid，输出tanh。 @fudanchenjiahao
