### ISSUE TITLE
找不到brc_eval和find_answer包，HELP

### ISSUE THREAD

**Issue by squirrel1982** [shiningliang/MRC2018#6]
感谢作者分享!
有个小问题请教，
MRC2018-master/BiDAF_Origin/dureader/utils/baseline_eval.py中，引入两个包
from brc_eval import compute_metrics_from_list
from find_answer import find_best_question_match
但我在代码中没发现这两个包，作者是不是漏了？

**Comment by shiningliang** [comment]
你好，感谢提问，这个baseline_eval.py没有被使用，在eval阶段使用的是dureader_eval，在官方最新[实现](https://github.com/baidu/DuReader/tree/master/tensorflow)中已经没有这个文件啦

**Comment by squirrel1982** [comment]
感谢这么迅速的回复，👍👍👍

发自我的vivo智能手机

Liang Shining <notifications@github.com>编写：

**Comment by shiningliang** [comment]
哈哈，刚好早上到实验室，查了一下邮件

<https://maas.mail.163.com/dashi-web-extend/html/proSignature.html?ftlId=1&name=lsnboost&uid=lsnboost%40outlook.com&iconUrl=http%3A%2F%2Fmail-online.nosdn.127.net%2Fsm5e60ceff986fff601dfbd21194bc66f7.jpg&items=%5B%22lsnboost%40outlook.com%22%5D>
[http://mail-online.nosdn.127.net/sm5e60ceff986fff601dfbd21194bc66f7.jpg]
lsnboost
lsnboost@outlook.com
签名由 网易邮箱大师<https://mail.163.com/dashi/dlpro.html?from=mail81> 定制
在2019年5月23日 09:18，squirrel1982<notifications@github.com><mailto:notifications@github.com> 写道：
感谢这么迅速的回复，👍👍👍

发自我的vivo智能手机

Liang Shining <notifications@github.com>编写：
